### ISSUE TITLE
Proposed rule changes

### ISSUE THREAD

**Issue by alaycock** [versett/eslint-plugin-versett#120]
**Problem description**

On ARCA we overrode a few rules we didn't find valuable, I wanted to propose them in a more general way.

### [`@typescript-eslint/array-type`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md)
**Proposed change:** 
```diff
// https://github.com/versett/eslint-plugin-versett/blob/master/rules/ts/on.js#L9
-     "@typescript-eslint/array-type": [2, { default: "generic" }],
+     "@typescript-eslint/array-type": [2, { default: "array-simple" }],
```
**Rationale:** 
I don't personally think that `Array<string>` is any less clear or obvious than `string[]`. Having the prefix `Array` is just makes lines longer without improving out codebase. That being said, if you're going to make a one-off type that is more complex, eg, `{ target: { value: string }}`, wrapping that with `Array<{ target: { value: string }}>` is better. It's easier to tell that a more complex type is an array with the `Array` prefix.

### [`@typescript-eslint/explicit-member-accessibility`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md)
**Proposed change:** 
```diff
// https://github.com/versett/eslint-plugin-versett/blob/b7bf50a3890be6716fe9e43e59a3db9cf12713fc/configurations/ts-react.js
  overrides: [
+    {
+      files: ["*.tsx"],
+      rules: {
+        "explicit-member-accessibility": 0
+      },
+    },
```
**Rationale:** 
In React `.tsx` files we don't need explicit member accessibility defined. Defining the accessibility of `render` doesn't make sense in the React context since we should never be calling component members directly. Alternately, we could just disable that rule altogether, since I haven't seen anyone define member accessibility in any projects.

### [`react/no-multi-comp`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-multi-comp.md)
**Proposed change:** 
```diff
// https://github.com/versett/eslint-plugin-versett/blob/b7bf50a3890be6716fe9e43e59a3db9cf12713fc/rules/react/on.js#L50
-    "react/no-multi-comp": 2,
+    "react/no-multi-comp": 0,
```
**Rationale:** 
Requiring components to exist in isolation in their own file adds unnecessary verbosity and clutter to our codebases. If you want to define a small component that's only used in one place, we shouldn't have rules to prevent that. If the file is getting unwieldily and long, then we should be using code reviews to enforce split files.
[The stance of one aggressive tweeter](https://twitter.com/ryanflorence/status/1133764204949729280)

### [`no-undefined`](https://eslint.org/docs/rules/no-undefined)
**Proposed change:** 
```diff
// https://github.com/versett/eslint-plugin-versett/blob/24a32a0e66477072e8cb96d05b02307869ed453e/rules/eslint/variables/on.js
-    "no-undefined": 2,
+    "no-undefined": 0,
```
**Rationale:** 
Why should this code fail eslint? Sometimes we want the state to be undefined. Not sure what the preferred alternative would be.
```
const defaultFormContext: FormState = {
  windPressure: undefined,
  membrane: undefined,
  attachment: undefined,
  manufacturers: undefined
};
```

### [`no-console`](https://eslint.org/docs/rules/no-console)
**Proposed change:** 
```diff
// https://github.com/versett/eslint-plugin-versett/blob/24a32a0e66477072e8cb96d05b02307869ed453e/rules/eslint/possible-errors/on.js#L16
-    "no-undefined": 2,
+    "no-undefined": [2, { "allow": ["error"] }],
```
**Rationale:** 
I think logging errors to the console is useful in production in smaller projects without robust logging tools. If something blows up in prod, being able to toss something into the console is helpful. 

I agree that we should prevent `console.log` from making it into production, but I think errors are okay.

**Comment by amandala** [comment]
I dislike the `react/jsx-props-no-spreading` rule because it forces the dev to explicitly type out every prop when we want to send the 'rest' through to another component leading to unnecessary verbosity. It also requires that the dev remember to add new props to that list of explicitly, as opposed to simply allowing them to become part of the 'rest'.
